default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: Pixlegram_development

test:
  <<: *default
  database: Pixlegram_test

production:
  <<: *default
  database: Pixlegram_production
  username: Pixlegram
  password: <%= ENV['PIXLEGRAM_DATABASE_PASSWORD'] %>
